### ISSUE TITLE
CavPack Rebuild

### ISSUE THREAD

**Issue by Smiggus** [7CavArma3Dev/7Cav-Alive-Altis#132]
Follow up on whether this is happening, or determine the root of the errors

**Comment by davidcit646** [comment]
Yeah it's happening. 

The cause of the crashes appears to be the result of the CavPack. Waldie and I have narrowed it down to the CavPack after a significant amount of testing on the dev server and on Tac2.

The assets that ALiVE is spawning _Doesn't Exist_ so it crashes. ALiVE thinks it does, because it should, but it doesn't. At least that's what I understand the situation as. Reference the fact that some MI24 Variants have tank cannons on them.

**Comment by Smiggus** [comment]
Understood, thanks Cit, do we have an expected time-line on this? Is this the official stance on the USAF matter then?

**Comment by davidcit646** [comment]
To my understanding, we're trying to un-fuck the mod pack. I think Waldie is trying to recreate the public cav addon.

**Comment by Smiggus** [comment]
I see, so for further clarification, which was the one causing issues in your testing? Cavpack or Gaming Community Addon (GCA)?

I take it from Waldie trying to rebuild GCA that it was the latter? However from my understanding of the setup, where is the other units ALiVE is trying to spawn from located in? Is that GCA as well or in CavPack?

I dont think CavPack would have much effect if any since we dont normally run that on Tac 2 but is definitely interesting to keep an eye on.

**Comment by davidcit646** [comment]
Its in the gaming community addon
